
title: My Resume
url: 'http://igorershov.me'
baseurl: '/Landing' #change it according to your repository name



# Profile information
yourname: Igor Ershov  ## put your name
title: 'SOFTWARE DEVELOPER &amp; STUDENT'  ## your title
location: Bologna, Italy
testprova: Ciao Mamma


## Social Profiles
facebook: https://www.facebook.com/PercheGuardiQuiGuardaSotto  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
